version: '3'

services:
 people:
   build:
     context: .
   ports:
     - "8000:8000"
   volumes:
     - ./stats:/stats
   command: >
      sh -c "export FLASK_APP=app &&
         export FLASK_ENV=development &&
         flask run "
   environment:
     - DB_HOST=db
     - DB_NAME=app
     - DB_USER=postgres
     - DB_PASS=supersecretpassword
   depends_on:
     - db
 db:
   image: postgres:10-alpine
   environment:
     - POSTGRES_DB=app
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=supersecretpassword